# Generated by Django 4.1.7 on 2023-04-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='lastt_name',
            new_name='last_name',
        ),
    ]
